name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      matrix:
        component:
        - "drivers/incluster"
        - "drivers/aws"
        - "drivers/ibm"
        - "may"

    defaults:
      run:
        working-directory: "./${{ matrix.component }}"

    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "${{ matrix.component }}/go.mod"

      - name: Running Tests
        run: |
          go mod tidy
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          flags: unit-tests
          files: ${{ matrix.component }}/cover.out
          fail_ci_if_error: false
